// Generated by gencpp from file rcr2018/DcmCommand.msg
// DO NOT EDIT!


#ifndef RCR2018_MESSAGE_DCMCOMMAND_H
#define RCR2018_MESSAGE_DCMCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rcr2018
{
template <class ContainerAllocator>
struct DcmCommand_
{
  typedef DcmCommand_<ContainerAllocator> Type;

  DcmCommand_()
    : cmd_vel(0.0)  {
    }
  DcmCommand_(const ContainerAllocator& _alloc)
    : cmd_vel(0.0)  {
  (void)_alloc;
    }



   typedef double _cmd_vel_type;
  _cmd_vel_type cmd_vel;





  typedef boost::shared_ptr< ::rcr2018::DcmCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcr2018::DcmCommand_<ContainerAllocator> const> ConstPtr;

}; // struct DcmCommand_

typedef ::rcr2018::DcmCommand_<std::allocator<void> > DcmCommand;

typedef boost::shared_ptr< ::rcr2018::DcmCommand > DcmCommandPtr;
typedef boost::shared_ptr< ::rcr2018::DcmCommand const> DcmCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcr2018::DcmCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcr2018::DcmCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rcr2018

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rcr2018': ['/home/pi/RCR/2018/ros_catkin_ws/src/rcr2018/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rcr2018::DcmCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcr2018::DcmCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcr2018::DcmCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcr2018::DcmCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcr2018::DcmCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcr2018::DcmCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcr2018::DcmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93e14900f3ac3cbfca813e5ff5e2bd6d";
  }

  static const char* value(const ::rcr2018::DcmCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93e14900f3ac3cbfULL;
  static const uint64_t static_value2 = 0xca813e5ff5e2bd6dULL;
};

template<class ContainerAllocator>
struct DataType< ::rcr2018::DcmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcr2018/DcmCommand";
  }

  static const char* value(const ::rcr2018::DcmCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcr2018::DcmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 cmd_vel\n\
\n\
";
  }

  static const char* value(const ::rcr2018::DcmCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcr2018::DcmCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DcmCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcr2018::DcmCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcr2018::DcmCommand_<ContainerAllocator>& v)
  {
    s << indent << "cmd_vel: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCR2018_MESSAGE_DCMCOMMAND_H
