// Generated by gencpp from file rcr2018/TofFront.msg
// DO NOT EDIT!


#ifndef RCR2018_MESSAGE_TOFFRONT_H
#define RCR2018_MESSAGE_TOFFRONT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rcr2018
{
template <class ContainerAllocator>
struct TofFront_
{
  typedef TofFront_<ContainerAllocator> Type;

  TofFront_()
    : front(0.0)  {
    }
  TofFront_(const ContainerAllocator& _alloc)
    : front(0.0)  {
  (void)_alloc;
    }



   typedef double _front_type;
  _front_type front;





  typedef boost::shared_ptr< ::rcr2018::TofFront_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcr2018::TofFront_<ContainerAllocator> const> ConstPtr;

}; // struct TofFront_

typedef ::rcr2018::TofFront_<std::allocator<void> > TofFront;

typedef boost::shared_ptr< ::rcr2018::TofFront > TofFrontPtr;
typedef boost::shared_ptr< ::rcr2018::TofFront const> TofFrontConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcr2018::TofFront_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcr2018::TofFront_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rcr2018

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rcr2018': ['/home/pi/RCR/2018/ros_catkin_ws/src/rcr2018/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rcr2018::TofFront_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcr2018::TofFront_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcr2018::TofFront_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcr2018::TofFront_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcr2018::TofFront_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcr2018::TofFront_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcr2018::TofFront_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea4f19e94f2ce3074d518ff4d026a5c8";
  }

  static const char* value(const ::rcr2018::TofFront_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea4f19e94f2ce307ULL;
  static const uint64_t static_value2 = 0x4d518ff4d026a5c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rcr2018::TofFront_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcr2018/TofFront";
  }

  static const char* value(const ::rcr2018::TofFront_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcr2018::TofFront_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 front\n\
\n\
";
  }

  static const char* value(const ::rcr2018::TofFront_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcr2018::TofFront_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TofFront_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcr2018::TofFront_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcr2018::TofFront_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<double>::stream(s, indent + "  ", v.front);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCR2018_MESSAGE_TOFFRONT_H
