// Generated by gencpp from file rcr2018/TofSide.msg
// DO NOT EDIT!


#ifndef RCR2018_MESSAGE_TOFSIDE_H
#define RCR2018_MESSAGE_TOFSIDE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rcr2018
{
template <class ContainerAllocator>
struct TofSide_
{
  typedef TofSide_<ContainerAllocator> Type;

  TofSide_()
    : right(0.0)
    , left(0.0)  {
    }
  TofSide_(const ContainerAllocator& _alloc)
    : right(0.0)
    , left(0.0)  {
  (void)_alloc;
    }



   typedef double _right_type;
  _right_type right;

   typedef double _left_type;
  _left_type left;





  typedef boost::shared_ptr< ::rcr2018::TofSide_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcr2018::TofSide_<ContainerAllocator> const> ConstPtr;

}; // struct TofSide_

typedef ::rcr2018::TofSide_<std::allocator<void> > TofSide;

typedef boost::shared_ptr< ::rcr2018::TofSide > TofSidePtr;
typedef boost::shared_ptr< ::rcr2018::TofSide const> TofSideConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcr2018::TofSide_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcr2018::TofSide_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rcr2018

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rcr2018': ['/home/pi/RCR/2018/ros_catkin_ws/src/rcr2018/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rcr2018::TofSide_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcr2018::TofSide_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcr2018::TofSide_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcr2018::TofSide_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcr2018::TofSide_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcr2018::TofSide_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcr2018::TofSide_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69961745475ae50d2f0b8ca4d0df065b";
  }

  static const char* value(const ::rcr2018::TofSide_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69961745475ae50dULL;
  static const uint64_t static_value2 = 0x2f0b8ca4d0df065bULL;
};

template<class ContainerAllocator>
struct DataType< ::rcr2018::TofSide_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcr2018/TofSide";
  }

  static const char* value(const ::rcr2018::TofSide_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcr2018::TofSide_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 right\n\
float64 left\n\
\n\
";
  }

  static const char* value(const ::rcr2018::TofSide_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcr2018::TofSide_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right);
      stream.next(m.left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TofSide_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcr2018::TofSide_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcr2018::TofSide_<ContainerAllocator>& v)
  {
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCR2018_MESSAGE_TOFSIDE_H
